# Generated by Django 4.0 on 2025-01-01 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_risk_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_stock_holding', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit_loss', models.CharField(max_length=50)),
                ('day_change', models.CharField(max_length=50)),
                ('portfolio_values', models.JSONField()),
                ('stock_distribution_by_sector', models.JSONField()),
                ('stock_distribution_by_company', models.JSONField()),
                ('stock_holdings', models.JSONField()),
                ('stock_suggestions', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='api.user')),
            ],
        ),
    ]
