# Generated by Django 4.0 on 2025-01-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stock_stockhistory'),
    ]

    operations = [
    ]
