# Generated by Django 4.0 on 2025-01-08 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_stock_id_alter_stock_sector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('circuit_breaker', models.CharField(max_length=20)),
                ('day_range', models.CharField(max_length=20)),
                ('fifty_two_week_range', models.CharField(max_length=20)),
                ('ask_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ask_volume', models.BigIntegerField()),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_volume', models.BigIntegerField()),
                ('ldcp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('var', models.DecimalField(decimal_places=2, max_digits=10)),
                ('haircut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('one_year_change', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ytd_change', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_statuses', to='api.stock')),
            ],
            options={
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
