# Generated by Django 4.0 on 2025-01-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stockstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstatus',
            name='ask_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='ask_volume',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='bid_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='bid_volume',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='change_percent',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='change_value',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='close_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='haircut',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='high',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='ldcp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='low',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='one_year_change',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='open_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='pe_ratio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='var',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='volume',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='ytd_change',
            field=models.CharField(max_length=20),
        ),
    ]
