# Generated by Django 4.0 on 2025-01-09 00:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_stockstatus_ask_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cdc_id',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_stock_holding', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit_loss', models.CharField(max_length=50)),
                ('profit_loss_value', models.CharField(max_length=50)),
                ('day_change', models.CharField(max_length=50)),
                ('stock_holding_details', models.JSONField()),
                ('cumulative_return_ytd', models.CharField(max_length=50)),
                ('cumulative_return_1yr', models.CharField(max_length=50)),
                ('cumulative_return_5yr', models.CharField(max_length=50)),
                ('risk_level_indicator', models.DecimalField(decimal_places=2, max_digits=15)),
                ('std', models.DecimalField(decimal_places=2, max_digits=15)),
                ('beta_coeffecient', models.DecimalField(decimal_places=2, max_digits=15)),
                ('var', models.DecimalField(decimal_places=2, max_digits=15)),
                ('market_sensitivity', models.CharField(max_length=50)),
                ('impact', models.CharField(max_length=50)),
                ('top_stocks', models.JSONField()),
                ('worst_stocks', models.JSONField()),
                ('transaction_history', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='api.user')),
            ],
        ),
    ]
