# Generated by Django 4.0 on 2025-01-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.CharField(max_length=20)),
                ('volume', models.CharField(max_length=50)),
                ('risk_level', models.CharField(max_length=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='api.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='api.user')),
            ],
        ),
    ]
