# Generated by Django 4.0 on 2025-01-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_watchlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'stock')},
        ),
    ]
