# Generated by Django 4.0 on 2025-01-09 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_watchlist_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fulfilled', models.BooleanField(default=False)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.watchlist')),
            ],
        ),
    ]
