# Generated by Django 4.0 on 2025-01-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_stockholding_remove_portfolio_user_delete_dashboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholding',
            name='price_buy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
